### ISSUE TITLE
Outputting to directories with spaces in them

### ISSUE THREAD

**Issue by jwbn** [deuteronomy-works/pyffmpeg#43]
Hi,

Not even sure if this is the right place to ask but you might know. I'm using the line
`ff.options('-i audio-{current_time}.mp4 -i video-{current_time}.mp4 -acodec copy -vcodec copy "{file_dir}/{underscore_name}.{prefformat}"') to convert files and to save them to a specific location. A directory for example being: C:/Users/X/Desktop/Test, this outputs completely fine.

However, when using a directory such as Program Files or one called 'Test Folder', ffmpeg is throwing an error. For example:
`subprocess.CalledProcessError: Command '['xx\\bin\\win32\\ffmpeg.exe', '-y', '-i', 'x.mp4', '-i', 'x.mp4', '-acodec', 'copy', '-vcodec', 'copy', 'C:/Users/x/Desktop/Tester', 'Folder/x"....mp4']' returned non-zero exit status 1`. From what I understand the space is causing ffmpeg to interpret everything after the space as another argument. I've tried using quotation marks etc but nothing seems to work.

Apologies if this is in the wrong place but I was wondering if you had any idea?

**Comment by amoh-godwin** [comment]
This is the right place for this.
The subprocess.CalledProcessError error has been solved. Please use the current version. Sorry for this

**Comment by jwbn** [comment]
I've upgraded to the latest version, still seem to have this issue. When subprocess is ran, the ffmpeg command appears to be split like this: [`C:/Users/X/Documents/Spaced`], ['Folder/somefile.mp4']. I'm trying to get it to accept it as ['C:/Users/X/Documents/Spaced Folder/somefile.mp4'].

**Comment by jwbn** [comment]
Edit:
I'm now trying 
`            ff.options(['-i', 'audio.mp4', '-i', 'video.mp4', '-acodec', 'copy',
                                '-vcodec', 'copy', 'C:\Users\X\Documents\Folder\test.mp4'])` and still can't seem to get it to work. Can't see any log output either like before.

**Comment by amoh-godwin** [comment]
Hello @jwbn please it has been fixed. Please test to see if it has been fixed in the `1.8.1` alpha release before we make a stable release.

https://pypi.org/project/pyffmpeg/1.8.1a0/#files

**Comment by jwbn** [comment]
Hi @amoh-godwin, I've updated to 1.8.1a0 and it is now working on my end. I've tested with no space folders and folders with space and they both now work correctly. Thank you very much for getting this fixed!

**Comment by amoh-godwin** [comment]
Thank you too @jwbn. I will now make a stable version. But it will just be a change from 1.8.1a0 to 1.8.1. Thank you again
